import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const tailwind_playground:NextPage = () => {
  return (
    <>
    <Head>
    <title>Tailwind Playground</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>


    </>
  )
}

export default tailwind_playground